name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install
        run: |
          pip install wheel isort black flake8
          pip setup.py bdist_wheel

      - run: isort --recursive --diff
      - run: run black --check .
      - run: run flake8
